// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: nrf-test

#ifndef _NRF_TEST_UI_H
#define _NRF_TEST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_watchface
void ui_watchface_screen_init(void);
void ui_event_watchface(lv_event_t * e);
extern lv_obj_t * ui_watchface;
extern lv_obj_t * ui_daymonth;
extern lv_obj_t * ui_timehhmmss;
extern lv_obj_t * ui_year;
extern lv_obj_t * ui_bluetooth;
void ui_event_brightness_slider(lv_event_t * e);
extern lv_obj_t * ui_brightness_slider;
// SCREEN: ui_settings
void ui_settings_screen_init(void);
void ui_event_settings(lv_event_t * e);
extern lv_obj_t * ui_settings;
extern lv_obj_t * ui_Colorwheel1;
// SCREEN: ui_stopwatch
void ui_stopwatch_screen_init(void);
void ui_event_stopwatch(lv_event_t * e);
extern lv_obj_t * ui_stopwatch;
extern lv_obj_t * ui_time;
void ui_event_start(lv_event_t * e);
extern lv_obj_t * ui_start;
void ui_event_stop(lv_event_t * e);
extern lv_obj_t * ui_stop;
extern lv_obj_t * ui_lap;
extern lv_obj_t * ui_startlabel;
extern lv_obj_t * ui_stoplabel;
void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;



LV_FONT_DECLARE(ui_font_MesloGLNerdFrontMono38);
LV_FONT_DECLARE(ui_font_MesloGLNerdFrontMono14);
LV_FONT_DECLARE(ui_font_MesloGLNerdFrontMono28);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
