// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: nrf-test

#include "ui.h"

#include "managers/display.hpp"

#include <zephyr/logging/log.h>

LOG_MODULE_REGISTER(nrf_test_lvgl, CONFIG_NRF_TEST_LOG_LEVEL);

void slidervc_fn(lv_event_t *e)
{
	lv_obj_t *slider = lv_event_get_target(e);
	auto value = lv_slider_get_value(slider);
	if (value != managers::display::Display::instance().get_brightness())
	{
		managers::display::Display::instance().set_brightness(value);
		LOG_DBG("%d", value);
	}
}
