// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: nrf-test

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void slidervc_fn(lv_event_t * e);
void startclicked(lv_event_t * e);
void stopclicked(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
