// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: nrf-test

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags

    ui_clocktime = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_clocktime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clocktime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_clocktime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_clocktime, "HH:MM:SS");
    lv_obj_set_style_text_font(ui_clocktime, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_daymonth = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_daymonth, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_daymonth, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_daymonth, 0);
    lv_obj_set_y(ui_daymonth, lv_pct(-9));
    lv_obj_set_align(ui_daymonth, LV_ALIGN_CENTER);
    lv_label_set_text(ui_daymonth, "DDD MMM DD YYYY");
    lv_obj_set_style_text_font(ui_daymonth, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_year = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_year, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_year, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_year, 0);
    lv_obj_set_y(ui_year, lv_pct(9));
    lv_obj_set_align(ui_year, LV_ALIGN_CENTER);
    lv_label_set_text(ui_year, "YYYY");
    lv_obj_set_style_text_font(ui_year, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

}
