// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: nrf-test

#include "ui.h"

void ui_settings_screen_init(void)
{
    ui_settings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Colorwheel1 = lv_colorwheel_create(ui_settings, true);
    lv_obj_set_width(ui_Colorwheel1, 150);
    lv_obj_set_height(ui_Colorwheel1, 150);
    lv_obj_set_align(ui_Colorwheel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Colorwheel1, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags

    lv_obj_add_event_cb(ui_settings, ui_event_settings, LV_EVENT_ALL, NULL);

}
