// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: nrf-test

#include "ui.h"

void ui_stopwatch_screen_init(void)
{
    ui_stopwatch = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_stopwatch, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_time = lv_label_create(ui_stopwatch);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time, 0);
    lv_obj_set_y(ui_time, lv_pct(-14));
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time, "00:00.000");
    lv_obj_set_style_text_font(ui_time, &ui_font_MesloGLNerdFrontMono38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_start = lv_btn_create(ui_stopwatch);
    lv_obj_set_width(ui_start, 70);
    lv_obj_set_height(ui_start, 40);
    lv_obj_set_x(ui_start, lv_pct(-18));
    lv_obj_set_y(ui_start, lv_pct(20));
    lv_obj_set_align(ui_start, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_start, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_start, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_stop = lv_btn_create(ui_stopwatch);
    lv_obj_set_width(ui_stop, 70);
    lv_obj_set_height(ui_stop, 40);
    lv_obj_set_x(ui_stop, lv_pct(18));
    lv_obj_set_y(ui_stop, lv_pct(20));
    lv_obj_set_align(ui_stop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_stop, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_stop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_stop, lv_color_hex(0x7F7F7F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_stop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lap = lv_label_create(ui_stopwatch);
    lv_obj_set_width(ui_lap, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lap, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lap, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lap, "00:00.000");
    lv_obj_set_style_text_color(ui_lap, lv_color_hex(0xCF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lap, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lap, &ui_font_MesloGLNerdFrontMono14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_startlabel = lv_label_create(ui_stopwatch);
    lv_obj_set_width(ui_startlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_startlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_startlabel, lv_pct(-18));
    lv_obj_set_y(ui_startlabel, lv_pct(20));
    lv_obj_set_align(ui_startlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_startlabel, "Start");
    lv_obj_set_style_text_font(ui_startlabel, &ui_font_MesloGLNerdFrontMono14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_stoplabel = lv_label_create(ui_stopwatch);
    lv_obj_set_width(ui_stoplabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_stoplabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_stoplabel, lv_pct(18));
    lv_obj_set_y(ui_stoplabel, lv_pct(20));
    lv_obj_set_align(ui_stoplabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_stoplabel, "Lap");
    lv_obj_set_style_text_font(ui_stoplabel, &ui_font_MesloGLNerdFrontMono14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_start, ui_event_start, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_stop, ui_event_stop, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_stopwatch, ui_event_stopwatch, LV_EVENT_ALL, NULL);

}
